const AUTH_PATTERN = {
  REGISTER: 'SPOTIFY_AUTH_REGISTER',
  LOGIN: 'SPOTIFY_AUTH_LOGIN',
  AUTHEN: 'SPOTIFY_AUTH_AUTHENTICATION',
};

const USER_PATTERN = {
  PROFILE: 'SPOTIFY_USER_PROFILE',
};

const SONG_PATTERN = {
  GET_BY_GENRE: 'SPOTIFY_SONG_GET_BY_GENRE',
};

export { AUTH_PATTERN, USER_PATTERN, SONG_PATTERN };
