const MICROSERVICE_URL = 'RABBITMQ_URL';
const AUTH_SERVICE_NAME = 'AUTH_SERVICE_NAME';
const AUTH_QUEUE = 'RABBITMQ_AUTH_QUEUE';
const USER_SERVICE_NAME = 'USER_SERVICE_NAME';
const USER_QUEUE = 'RABBITMQ_USER_QUEUE';
const SONG_SERVICE_NAME = 'SONG_SERVICE_NAME';
const SONG_QUEUE = 'RABBITMQ_SONG_QUEUE';
const ARTIST_SERVICE_NAME = 'ARTIST_SERVICE_NAME';
const ARTIST_QUEUE = 'RABBITMQ_ARTIST_QUEUE';

export {
  MICROSERVICE_URL,
  AUTH_SERVICE_NAME,
  AUTH_QUEUE,
  USER_SERVICE_NAME,
  USER_QUEUE,
  SONG_SERVICE_NAME,
  SONG_QUEUE,
  ARTIST_SERVICE_NAME,
  ARTIST_QUEUE,
};
