const TAG_ACTIVE_FRIEND = 'ACTIVE_FRIEND';
const TAG_UPDATE_ACTIVE_STATUS = 'UPDATE_ACTIVE_STATUS';
const TAG_GET_ALL_CONVERSATION = 'GET_ALL_CONVERSATION';
const TAG_SEND_MESSAGE = 'SEND_MESSAGE';
const TAG_GET_NEW_MESSAGE = 'GET_NEW_MESSAGE';

export {
  TAG_ACTIVE_FRIEND,
  TAG_UPDATE_ACTIVE_STATUS,
  TAG_GET_ALL_CONVERSATION,
  TAG_SEND_MESSAGE,
  TAG_GET_NEW_MESSAGE,
};
